### ISSUE TITLE
ValueError: Parent directory of lenet doesn't exist, can't save. 

### ISSUE THREAD

**Issue by bauer-san** [udacity/CarND-LeNet-Lab#10]
To solve this locally, I replaced the line:
saver.save(sess, 'lenet') 
with 
saver.save(sess, '.\lenet')

**Comment by anthony-chaudhary** [comment]
Thank you very much, this fix worked for me too.
On a windows machine.

**Comment by anujshah1003** [comment]
That fixed my error too
