### ISSUE TITLE
environment.yml is missing

### ISSUE THREAD

**Issue by ghost** [udacity/CarND-LeNet-Lab#8]
`conda env create -f environment.yml` fails because environment.yml is not in the repo

**Comment by usr54391** [comment]
Right its missing. This was opened up 8 days ago and its still missing.

Can the instructors take a look at it and try to fix this, or are students expected to remain stuck on these issues and not able to get some progress on the program?

**Comment by jihobak** [comment]
I thinks these are enough,

name: CarND-LeNet-Lab
dependencies:
- pip >= 9
- jupyter
- scikit-learn
- numpy
- matplotlib
- pip:
- tensorflow >= 0.12.0rc1

**Comment by domluna** [comment]
@ryadav-duo Try using this https://github.com/udacity/CarND-Term1-Starter-Kit instead, it's meant to be used for the whole term. Follow https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md for the anaconda setup.
